        @Override
        public void run() {
            Looper.prepare();
            try {
                initRealm();
                setLooper(Looper.myLooper());
                base.evaluate();
                Looper.loop();
            } catch (Throwable t) {
                setAssertionError(t);
                setUnitTestFailed();

                // If an exception occurred, `looperThread.testComplete()` was probably no called.
                // Rerun it here, but ignore any failures as the first failure is more important.
                try {
                    closeTestResources();
                } catch (Throwable ignore) {
                }
            }
        }

